version: "3.4"
networks:
  pypi_bot:

services:
  main:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile
      target: main
    depends_on:
      - redis
    networks:
      - pypi_bot
  scheduler:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile
      target: scheduler
    depends_on:
      - redis
    networks:
      - pypi_bot
  redis:
    image: redis:5.0.5
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis/data:/data
    ports:
      # for local test set "6379:6379"
      - 6379
    networks:
      - pypi_bot