FROM python:3.7.7 as base
RUN pip install poetry
WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY pypi_tools/models.py pypi_tools/admin.py  /app/

COPY ./wait_for.py /wait_for.py
CMD python /wait_for.py && python /app/admin.py