version: "3"
services:
  postgres:
    image: postgres:11.5
    container_name: postgres
    env_file:
      - ./pypi_tools/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  admin:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile-admin
    ports:
      - "5555:5555"
    depends_on:
      - postgres
  main:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5455:5455"
    depends_on:
      - postgres