version: "3"
services:
  postgres:
    image: postgres:11.5
    container_name: postgres
    env_file:
      - ./pypi_tools/.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
  admin:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile-admin
    ports:
      - "5555:5555"
    depends_on:
      - postgres
  main:
    env_file:
      - ./pypi_tools/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5455:5455"
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:5.0.5
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379